In [1]:
import numpy as np

# Simple exercises with matrices

In [2]:
A=np.array([[2,3],[1,-1]])
print(A)

[[ 2  3]
 [ 1 -1]]


## Read and write from a file

### As text files

In [3]:
def write_matrix_to_file(matrix, filename):
    
    #This function don't necessarily have to include a return statement 
    
    with open(filename, 'w') as file:
        
        for row in matrix:
            
            row_str = ' '.join(map(str, row))
            file.write(row_str + '\n')

write_matrix_to_file(A, 'matrixA.txt')

We have used the map function which applies a specified function to all items in an iterable (e.g., a list, tuple, or other iterable) and returns an iterable map object.

In [4]:
A = [1, 2, 3, 4, 5]

Asqr = map(lambda x: x**2, A) # lambda function, one-liner

Asqr = list(Asqr)

print(Asqr)

[1, 4, 9, 16, 25]


In [5]:
def read_matrix_from_file(filename):
    
    import numpy as np
    
    matrix = []
    
    with open(filename, 'r') as file:
        
        for line in file:
            
            row = list(map(int, line.strip().split()))
            matrix.append(row)
            
    matrix=np.array(matrix)
    
    return matrix

B = read_matrix_from_file('matrixA.txt')
print(B)

[[ 2  3]
 [ 1 -1]]


### Numpy files

In [6]:
np.save('matrixA.npy', A)

B = np.load('matrixA.npy')
print(B)

[1 2 3 4 5]


# Matrix addition/subtraction, scalar multiplication

In [7]:
A=np.array([[2,-1.5],[3,7]])
B=np.array([[1,-1],[2,-1]])

### Matrix addition as a vector operation on numpy arrays

In [8]:
A+B

array([[ 3. , -2.5],
       [ 5. ,  6. ]])

In [9]:
C=A+B
C

array([[ 3. , -2.5],
       [ 5. ,  6. ]])

### numpy `add` function

In [10]:
np.add(A,B)

array([[ 3. , -2.5],
       [ 5. ,  6. ]])

In [11]:
np.shape(A)

(2, 2)

In [12]:
def add_matrices(A, B):
    
    # Check if matrices have the same dimensions
    if np.shape(A) != np.shape(B):
        raise ValueError("Matrices must have the same dimensions for addition.")

    N_rows=np.shape(A)[0]
    N_cols=np.shape(A)[1]
    
    # Initialize C-vector with zero
    C=np.zeros((N_rows,N_cols))
    
    # Perform element-wise addition
    for i in range(N_rows):
        for j in range(N_cols):
            C[i][j] = A[i][j] + B[i][j]

    return C

In [13]:
C=add_matrices(A, B)
C

array([[ 3. , -2.5],
       [ 5. ,  6. ]])

In [14]:
D=A-B
D

array([[ 1. , -0.5],
       [ 1. ,  8. ]])

In [15]:
t=0.1
E=t*A
E

array([[ 0.2 , -0.15],
       [ 0.3 ,  0.7 ]])

# Special matrices for initialization

In [16]:
import numpy as np
from scipy.linalg import toeplitz

# 1. Identity Matrix
identity_matrix = np.eye(3)
print("1. Identity matrix:")
print(identity_matrix)

# 2. Zero Matrix
zero_matrix = np.zeros((2, 3))
print("\n2. Zero matrix:")
print(zero_matrix)

# 3. Ones Matrix
ones_matrix = np.ones((3, 2))
print("\n3. Ones matrix:")
print(ones_matrix)

# 4. Diagonal Matrix
diagonal_matrix = np.diag([1, 2, 3])
print("\n4. Diagonal matrix:")
print(diagonal_matrix)

# 5. Random Matrix
random_matrix = np.random.rand(2, 2)
print("\n5. Random matrix:")
print(random_matrix)

# 6. Full Matrix
full_matrix = np.full((2, 3), 7)
print("\n6. Full matrix:")
print(full_matrix)

# 7. Toeplitz Matrix (a square Toeplitz matrix is circulant)
first_row = [1, 2, 3]
toeplitz_matrix = toeplitz(first_row)
print("\n7. Toeplitz matrix:")
print(toeplitz_matrix)


1. Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

2. Zero matrix:
[[0. 0. 0.]
 [0. 0. 0.]]

3. Ones matrix:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

4. Diagonal matrix:
[[1 0 0]
 [0 2 0]
 [0 0 3]]

5. Random matrix:
[[0.22371414 0.3424747 ]
 [0.19533369 0.00235501]]

6. Full matrix:
[[7 7 7]
 [7 7 7]]

7. Toeplitz matrix:
[[1 2 3]
 [2 1 2]
 [3 2 1]]


# Matrix-vector multiplication

In [17]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

x = np.array([2, 3, 4])

# Matrix-vector multiplication using numpy.dot function
b = np.dot(A, x)

print("Result using numpy.dot function:")
print(b)

# Matrix-vector multiplication using @ operator (equivalent to numpy.dot)
b = A @ x

print("\nResult using @ operator:")
print(b)

Result using numpy.dot function:
[20 47 74]

Result using @ operator:
[20 47 74]


In [18]:
def matvec(A, x):
    
    if np.shape(A)[1] != len(x):
        raise ValueError("Matrix and vector are not conformable")

    # Perform element-wise addition
    N_rows=np.shape(A)[0]
    N_cols=np.shape(A)[1]
    
    b=np.zeros((N_rows))
    
    for i in range(N_rows):
        
        # b[i]=0
        # for j in range(N_cols):
        #    b[i] = b[i] + A[i][j] * x[j]
        
        b[i]=np.dot(A[i][:],x[:])

    return b

In [19]:
b=matvec(A,x)
b

array([20., 47., 74.])

In [20]:
def matvec2(A, x):
    # as a linear combination of columns of A
    
    if np.shape(A)[1] != len(x):
        raise ValueError("Matrix and vector are not conformable")

    # Perform element-wise addition
    N_rows=np.shape(A)[0]
    N_cols=np.shape(A)[1]
    
    b=np.zeros((N_rows))

    for j in range(N_cols):
        b = b + A[:][j] * x[j]

    return b

In [21]:
b=matvec(A,x)
b

array([20., 47., 74.])

# Matrix-matrix multiplication

In [22]:
def matrix_multiply(A, B):
    
    # Check conformability
    if A.shape[1] != B.shape[0]:
        raise ValueError("Matrices are not conformable for multiplication.")

    # Perform matrix-matrix multiplication
    C = np.dot(A, B)

    return C

A = np.array([[1,2,3],[0,3,-1]])
B = np.array([[1,2],[0,-2],[1,0]])

C = matrix_multiply(A, B)

print("AB:")
print(C)

D = matrix_multiply(B, A)

print("BA:")
print(D)

AB:
[[ 4 -2]
 [-1 -6]]
BA:
[[ 1  8  1]
 [ 0 -6  2]
 [ 1  2  3]]
