In [1]:
import numpy as np

In [2]:
a=[1,3,2,0,4,5,6,3]
a=np.array(a)

# Basic Operations

In [3]:
sum_a = np.sum(a)
max_a = np.amax(a)
min_a = np.amin(a)
mean_a = np.mean(a)
median_a = np.median(a)
std_a = np.std(a)
var_a = np.var(a)

fstr = "{:15.8f}".format(sum_a)
print(fstr)

fstr = "{:15.8f} {:15.8f}".format(max_a, min_a)
print(fstr)

fstr = "{:15.8f} {:15.8f} {:15.8f} {:15.8f}".format(mean_a, median_a, std_a, var_a)
print(fstr)

    24.00000000
     6.00000000      0.00000000
     3.00000000      3.00000000      1.87082869      3.50000000


# Indexing and Sorting

In [4]:
max_ind = np.argmax(a, axis=0)
min_ind = np.argmin(a, axis=0)

fstr = "{:15.8f} {:15.8f}".format(max_ind, min_ind)
print(fstr)

     6.00000000      3.00000000


In [5]:
sorted_ind_incr = np.argsort(a)
sorted_ind_decr = np.argsort(a)[::-1]

print(sorted_ind_incr, sorted_ind_decr)

[3 0 2 1 7 4 5 6] [6 5 4 7 1 2 0 3]


# Finding Elements

In [6]:
condition_ind = np.where(a>3)
non_zero_ind = np.nonzero(a)

print(condition_ind,non_zero_ind)

(array([4, 5, 6]),) (array([0, 1, 2, 4, 5, 6, 7]),)


# Reshaping and Manipulation

In [7]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A_transpose = np.transpose(A)
print(A_transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [8]:
rows, columns = 2, 4
reshaped_a = np.reshape(a, (rows, columns))
print(a)
print(reshaped_a)

[1 3 2 0 4 5 6 3]
[[1 3 2 0]
 [4 5 6 3]]


In [9]:
array1 = np.array([1, 2, 3])
array2 = np.array([2, 3, 4, 0])

concatenated_arrays = np.concatenate([array1, array2], axis=0)
print(concatenated_arrays)

[1 2 3 2 3 4 0]


In [10]:
sub_arrays = np.split(a, 2)  # Split into 2 equal parts
print(sub_arrays)

[array([1, 3, 2, 0]), array([4, 5, 6, 3])]


# Matrix Operations

In [11]:
diagonal_elements = np.diagonal(A)
print(diagonal_elements)

trace_A = np.trace(A)
print(trace_A)

B = np.array([[1, 5, 0], [0, 2, 6], [7, 2, 1]])

AtimesB = np.dot(A, B)
print(AtimesB)


[1 5 9]
15
[[22 15 15]
 [46 42 36]
 [70 69 57]]


# Creating Arrays

In [12]:
start, stop, num_points = 0, 1, 10

evenly_spaced_values = np.linspace(start, stop, num_points)
print(evenly_spaced_values)

step = 0.1

step_values = np.arange(start, stop, step)
print(step_values)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


# Random Values

In [13]:
random_uniform = np.random.rand(5, 5)  # 5x5 array of random values [0, 1)
print(random_uniform)

[[0.73908834 0.54620019 0.99370087 0.02661478 0.36678185]
 [0.66263989 0.43170911 0.0099736  0.93107488 0.5657724 ]
 [0.94774808 0.71843446 0.44667832 0.91418218 0.46781264]
 [0.82600642 0.83822762 0.63100035 0.97272971 0.85262239]
 [0.2880084  0.49634573 0.38038047 0.16989366 0.80525861]]


In [14]:
random_normal = np.random.randn(5, 5)  # 5x5 array of random values from standard normal distribution
print(random_normal)

[[ 2.08821838  1.1228885   0.67657747 -1.4563589  -1.19255518]
 [ 0.05505173 -0.43632741  0.38188656  1.05021421 -0.26251961]
 [ 0.23716185  0.66440537 -1.75806472 -0.97838477 -1.82932643]
 [-0.15270644 -0.81599204 -0.98639555  0.82662991 -0.21141442]
 [ 0.6014964   1.57567143  0.24671443  0.01638271  0.9372587 ]]


# Miscellaneous

In [15]:
a=[1,3,2,0,4,5,6,3]
a=np.array(a)

min_val = 2
max_val = 5
clipped_array = np.clip(a, min_val, max_val) #  Clip (limit) the values in an array.

print(a)
print(clipped_array)

[1 3 2 0 4 5 6 3]
[2 3 2 2 4 5 5 3]


Values less than `min_val` are set to `min_val` and values greater than `max_val` are set to `max_val`.

In [16]:
array1 = np.array([1, 2, 3])
array2 = np.array([2, 3, 4, 0])

intersection = np.intersect1d(array1, array2)
print(intersection)

[2 3]


In [17]:
array1 = np.array([1, 2, 3])
array2 = np.array([2, 3, 4, 0])

union = np.union1d(array1, array2)
print(union)

[0 1 2 3 4]


In [18]:
unique_values, counts = np.unique(a, return_counts=True)
print(unique_values, counts)

[0 1 2 3 4 5 6] [1 1 1 2 1 1 1]
